/*
 * gui.cpp
 *
 *  Created on: Sep 28, 2012
 *      Author: bholland
 */

/********************************************************************************
** Form generated from reading UI file 'simtoexp_mwz13889.ui'
**
** Created
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef SIMTOEXP_MWZ13889_H
#define SIMTOEXP_MWZ13889_H


//includes automatically generated by Qt Designer
#include <QtCore/QVariant>
#include <QtGlobal>
#if QT_VERSION >= 0x050000
    #include <QtWidgets/QAction>
    #include <QtWidgets/QApplication>
    #include <QtWidgets/QButtonGroup>
    #include <QtWidgets/QCheckBox>
    #include <QtWidgets/QFrame>
    #include <QtWidgets/QGridLayout>
    #include <QtWidgets/QHBoxLayout>
    #include <QtWidgets/QHeaderView>
    #include <QtWidgets/QLabel>
    #include <QtWidgets/QLineEdit>
    #include <QtWidgets/QMainWindow>
    #include <QtWidgets/QMenu>
    #include <QtWidgets/QMenuBar>
    #include <QtWidgets/QPushButton>
    #include <QtWidgets/QSpacerItem>
    #include <QtWidgets/QStatusBar>
    #include <QtWidgets/QVBoxLayout>
    #include <QtWidgets/QWidget>
    #include <QtWidgets/QGroupBox>
#else
    #include <QtGui/QAction>
    #include <QtGui/QApplication>
    #include <QtGui/QButtonGroup>
    #include <QtGui/QCheckBox>
    #include <QtGui/QFrame>
    #include <QtGui/QGridLayout>
    #include <QtGui/QHBoxLayout>
    #include <QtGui/QHeaderView>
    #include <QtGui/QLabel>
    #include <QtGui/QLineEdit>
    #include <QtGui/QMainWindow>
    #include <QtGui/QMenu>
    #include <QtGui/QMenuBar>
    #include <QtGui/QPushButton>
    #include <QtGui/QSpacerItem>
    #include <QtGui/QStatusBar>
    #include <QtGui/QVBoxLayout>
    #include <QtGui/QWidget>
    #include <QtGui/QGroupBox>
#endif

#include <qwt/qwt_plot.h>
#include <qwt/qwt_plot_canvas.h>

#include "scrollzoomer.h"
#include "TabWidgetCloseable.h"

QT_BEGIN_NAMESPACE

const int COMPONENT_COLUMNS = 7;
const int COMPONENT_ROWS = 10;

//for component labels
const int CMP_ID_INDEX = 0;
const int CMP_NATOMS_INDEX = 1;
const int CMP_ATOMS_PGROUP_INDEX = 2;
const int CMP_NGROUPS_INDEX = 3;
const int CMP_NELEC_PGROUP_INDEX = 4;
const int CMP_NSLD_PGROUP_INDEX = 5;
const int CMP_VOLUME_PGROUP_INDEX = 6;


class Ui_MainWindow
{
public:

	//a lot auto-generated by QtDesigner, so a little messy
	//File
    QAction *actionExit;
    QAction *actionSIMtoEXP_format;
    QAction *actionTrajFiles;
    QAction *actionX_ray;
    QAction *actionNeutron;
    QAction *actionElectron_density_profile;
    QAction *actionNeutron_Scattering_Length_Density;
    QAction *actionComponent_file;
    QAction *actionDeleteSim; //BH
    QAction *actionDeleteED;
    QAction *actionDeleteNSLD;
    QAction *actionDeleteXray1; //BH
    QAction *actionDeleteXray2; //BH
    QAction *actionDeleteXray3; //BH ...
    QAction *actionDeleteXray4;
    QAction *actionDeleteXray5;
    QAction *actionDeleteNeutron1;
    QAction *actionDeleteNeutron2;
    QAction *actionDeleteNeutron3;
    QAction *actionDeleteNeutron4;
    QAction *actionDeleteNeutron5;
    QAction *actionDeleteComponents;//BH

    //Tools
    QAction *actionScattering_lengths;
    QAction *action_Atomic_form_factors;
    QAction *actionSi_mulation_specifics;
    QAction *action_Analysis;
    //Tools -> Export
    QAction *action_X_ray_form_factors;
    QAction *actionNeutron_form_factors;

    QAction *actionElementalElectron_density;
    QAction *actionComponentElectron_density;

    QAction *actionElementalNeutron_SL_density;
    QAction *actionComponentNeutron_SL_density;

    QAction *actionVolumetric_fit;

    QAction *actionElementalNumb_density;
    QAction *actionParticleNumb_density;
    QAction *actionComponentNumb_density;
    QAction *actionEverything;

    //Plot
    QAction *actionTogglePlot;
    QAction *actionFitToWindow;
    //Plot->Advanced (manual axis set up)
    QAction *actionPlotAdvanced;
    QAction *actionAbout_SIMtoEXP;
    QAction *actionUser_manual;
    QAction *actionLicense;
    QWidget *centralwidget;

    //Grid layouts and tab objects
    QGridLayout *main_grid;
    TabWidgetCloseable *tabWidget;
    QWidget *e_densities_tab;
    QGridLayout *e_densities_grid;
    QwtPlot *e_densities_plot;
    ScrollZoomer *e_densities_scroll;
    QWidget *neutron_SL_tab;
    QGridLayout *neutron_SL_grid;
    QwtPlot *neutron_SL_plot;
    ScrollZoomer *neutron_SL_scroll;
    QWidget *xray_formfactors_tab;
    QGridLayout *xray_formfactors_grid;
    QwtPlot *xray_formfactors_plot;
    ScrollZoomer *xray_formfactors_scroll;
    QWidget *neutron_formfactors_tab;
    QGridLayout *neutron_formfactors_grid;
    QwtPlot *neutron_formfactors_plot;
    ScrollZoomer *neutron_formfactors_scroll;
    QWidget *num_densities_tab;
    QGridLayout *num_densities_grid;
    QwtPlot *num_densities_plot;
    ScrollZoomer *num_densities_scroll;
    QWidget *vol_probs_tab;
    QGridLayout *vol_probs_grid;
    QwtPlot *vol_probs_plot;
    ScrollZoomer *vol_probs_scroll;
    QFrame *margins_frame;
    QLabel *margins_label;
    QHBoxLayout *margins_horizontalLayout;
    QLabel *left_label;
    QLineEdit *left_margin_lineEdit;
    QLabel *right_label;
    QLineEdit *right_margin_lineEdit;
    QPushButton *calc_volume_button;
    QLabel *rms_label;
    QLineEdit *vol_rms_lineEdit;
    QWidget *layoutWidget;
    QPushButton *fourier_button;
    QCheckBox *sym_checkBox;
    QPushButton *defaults_button;
    QLabel *solv_ed_label;
    QLineEdit *solv_ed_lineEdit;
    QLabel *solv_nsld_label;
    QLineEdit *solv_nsld_lineEdit;
    QLabel *q_int_label;
    QLabel *low_label;
    QLabel *high_label;
    QLabel *step_label;
    QLabel *xray_int_label;
    QLineEdit *xray_qlow_lineEdit;
    QLineEdit *xray_qhigh_lineEdit;
    QLineEdit *xray_qstep_lineEdit;
    QLabel *neutron_int_label;
    QLineEdit *neut_qlow_lineEdit;
    QLineEdit *neut_qhigh_lineEdit;
    QLineEdit *neut_qstep_lineEdit;

    QLabel *xray_sample_label;
    QPushButton *xray_scale_button;
    QLabel *xray_chi_label;
    QLabel *xray_sam1_label;
    QLineEdit *xray_scale_sam1_lineEdit;
    QLineEdit *xray_chi_sam1_lineEdit;
    QLabel *xray_sam2_label;
    QLineEdit *xray_scale_sam2_lineEdit;
    QLineEdit *xray_chi_sam2_lineEdit;
    QLabel *xray_sam3_label;
    QLineEdit *xray_scale_sam3_lineEdit;
    QLineEdit *xray_chi_sam3_lineEdit;
    QLabel *xray_sam4_label;
    QLineEdit *xray_scale_sam4_lineEdit;
    QLineEdit *xray_chi_sam4_lineEdit;
    QLabel *xray_sam5_label;
    QLineEdit *xray_scale_sam5_lineEdit;
    QLineEdit *xray_chi_sam5_lineEdit;
    QLabel *neut_sample_label;
    QPushButton *neut_scale_button;
    QLabel *neut_chi_label;
    QLabel *neut_sam1_label;
    QLineEdit *neut_scale_sam1_lineEdit;
    QLineEdit *neut_chi_sam1_lineEdit;
    QLabel *neut_sam2_label;
    QLineEdit *neut_scale_sam2_lineEdit;
    QLineEdit *neut_chi_sam2_lineEdit;
    QLabel *neut_sam3_label;
    QLineEdit *neut_scale_sam3_lineEdit;
    QLineEdit *neut_chi_sam3_lineEdit;
    QLabel *neut_sam4_label;
    QLineEdit *neut_scale_sam4_lineEdit;
    QLineEdit *neut_chi_sam4_lineEdit;
    QLabel *neut_sam5_label;
    QLineEdit *neut_scale_sam5_lineEdit;
    QLineEdit *neut_chi_sam5_lineEdit;
    QMenuBar *menubar;
    QMenu *menu_File;
    QMenu *menuOpen;
    QMenu *menuSimulation_data;
    QMenu *menuStructureFactor_data;
    QMenu *menuDelete; //BH
    QMenu *menuXrayDelete; //BH
    QMenu *menuNeutronDelete; //BH
    QMenu *menu_Tools;
    QMenu *menuE_xport;
    QMenu *menuExpNumberDensity;
    QMenu *menuExpElectDensity;
    QMenu *menuExpNSLDensity;
    QMenu *menu_Window;
    QMenu *menu_Help;
    QStatusBar *statusbar;

    //Group boxes and layouts used for the bottom portion of the GUI
    QGroupBox *margins;
    QGroupBox *simFormFactors;
    QGroupBox *expFormFactors;
    QGroupBox *components;
    QGridLayout *simGrid;
    QGridLayout *expGrid;
    QGridLayout *componentGrid;
    QHBoxLayout *fourierLayout;
    QHBoxLayout *volumeLayout;

    //Containers for component QLineEdit objects
    QList<QLineEdit*> id_edits;
    QList<QLineEdit*> natoms_edits;
    QList<QLineEdit*> atoms_pgroup_edits;
    QList<QLineEdit*> ngroups_edits;
    QList<QLineEdit*> nelec_pgroup_edits;
    QList<QLineEdit*> nsld_pgroup_edits;
    QList<QLineEdit*> volume_edits;
    QList<QList<QLineEdit*>* > cmp_edits; //to simplify code below
    QList<QLabel*> cmp_labels;

    void populateComponentContainers() {

    	cmp_edits.append(&id_edits);
    	cmp_edits.append(&natoms_edits);
    	cmp_edits.append(&atoms_pgroup_edits);
    	cmp_edits.append(&ngroups_edits);
    	cmp_edits.append(&nelec_pgroup_edits);
    	cmp_edits.append(&nsld_pgroup_edits);
    	cmp_edits.append(&volume_edits);
    }

    void setupUi(QMainWindow *MainWindow)
    {
    	populateComponentContainers();

        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(981, 740);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionSIMtoEXP_format = new QAction(MainWindow);
        actionSIMtoEXP_format->setObjectName(QString::fromUtf8("actionSIMtoEXP_format"));
        actionTrajFiles = new QAction(MainWindow);
        actionTrajFiles->setObjectName(QString::fromUtf8("actionTrajFiles"));
        actionX_ray = new QAction(MainWindow);
        actionX_ray->setObjectName(QString::fromUtf8("actionX_ray"));
        actionNeutron = new QAction(MainWindow);
        actionNeutron->setObjectName(QString::fromUtf8("actionNeutron"));
        actionDeleteSim = new QAction(MainWindow);
        actionDeleteSim->setObjectName(QString::fromUtf8("actionDeleteSim"));
		actionDeleteED = new QAction(MainWindow);
        actionDeleteED->setObjectName(QString::fromUtf8("actionDeleteED"));
        actionDeleteNSLD = new QAction(MainWindow);
        actionDeleteNSLD->setObjectName(QString::fromUtf8("actionDeleteNSLD"));
		actionDeleteXray1 = new QAction(MainWindow);
		actionDeleteXray1->setObjectName(QString::fromUtf8("actionDeleteXray1"));
		actionDeleteXray2 = new QAction(MainWindow);
		actionDeleteXray2->setObjectName(QString::fromUtf8("actionDeleteXray2"));
		actionDeleteXray3 = new QAction(MainWindow);
		actionDeleteXray3->setObjectName(QString::fromUtf8("actionDeleteXray3"));
		actionDeleteXray4 = new QAction(MainWindow);
		actionDeleteXray4->setObjectName(QString::fromUtf8("actionDeleteXray4"));
		actionDeleteXray5 = new QAction(MainWindow);
		actionDeleteXray5->setObjectName(QString::fromUtf8("actionDeleteXray5"));
		actionDeleteNeutron1 = new QAction(MainWindow);
		actionDeleteNeutron1->setObjectName(QString::fromUtf8("actionDeleteNeutron1"));
		actionDeleteNeutron2 = new QAction(MainWindow);
		actionDeleteNeutron2->setObjectName(QString::fromUtf8("actionDeleteNeutron2"));
		actionDeleteNeutron3 = new QAction(MainWindow);
		actionDeleteNeutron3->setObjectName(QString::fromUtf8("actionDeleteNeutron3"));
		actionDeleteNeutron4 = new QAction(MainWindow);
		actionDeleteNeutron4->setObjectName(QString::fromUtf8("actionDeleteNeutron4"));
		actionDeleteNeutron5 = new QAction(MainWindow);
		actionDeleteNeutron5->setObjectName(QString::fromUtf8("actionDeleteNeutron5"));
        actionDeleteComponents = new QAction(MainWindow);
        actionDeleteComponents->setObjectName(QString::fromUtf8("actionDeleteComponents"));

        actionElectron_density_profile = new QAction(MainWindow);
        actionElectron_density_profile->setObjectName(QString::fromUtf8("actionElectron_density_profile"));
        actionNeutron_Scattering_Length_Density = new QAction(MainWindow);
        actionNeutron_Scattering_Length_Density->setObjectName(QString::fromUtf8("actionNeutron_Scattering_Length_Density"));
        actionComponent_file = new QAction(MainWindow);
        actionComponent_file->setObjectName(QString::fromUtf8("actionComponent_file"));
        action_Atomic_form_factors = new QAction(MainWindow);
        action_Atomic_form_factors->setObjectName(QString::fromUtf8("action_Atomic_form_factors"));
        actionSi_mulation_specifics = new QAction(MainWindow);
        actionSi_mulation_specifics->setObjectName(QString::fromUtf8("actionSi_mulation_specifics"));
        action_Analysis = new QAction(MainWindow);
        action_Analysis->setObjectName(QString::fromUtf8("action_Analysis"));
        action_X_ray_form_factors = new QAction(MainWindow);
        action_X_ray_form_factors->setObjectName(QString::fromUtf8("action_X_ray_form_factors"));
        actionNeutron_form_factors = new QAction(MainWindow);
        actionNeutron_form_factors->setObjectName(QString::fromUtf8("actionNeutron_form_factors"));
        actionElementalElectron_density = new QAction(MainWindow);
        actionElementalElectron_density->setObjectName(QString::fromUtf8("actionElementalElectron_density"));
        actionComponentElectron_density = new QAction(MainWindow);
        actionComponentElectron_density->setObjectName(QString::fromUtf8("actionComponentElectron_density"));
        actionElementalNeutron_SL_density = new QAction(MainWindow);
        actionElementalNeutron_SL_density->setObjectName(QString::fromUtf8("actionElementalNeutron_SL_density"));
        actionComponentNeutron_SL_density = new QAction(MainWindow);
        actionComponentNeutron_SL_density->setObjectName(QString::fromUtf8("actionComponentNeutron_SL_density"));
        actionVolumetric_fit = new QAction(MainWindow);
        actionVolumetric_fit->setObjectName(QString::fromUtf8("actionVolumetric_fit"));
        actionElementalNumb_density = new QAction(MainWindow);
        actionElementalNumb_density->setObjectName(QString::fromUtf8("actionNumb_density"));
        actionParticleNumb_density = new QAction(MainWindow);
        actionParticleNumb_density->setObjectName(QString::fromUtf8("actionParticleNumb_density"));
        actionComponentNumb_density = new QAction(MainWindow);
        actionComponentNumb_density->setObjectName(QString::fromUtf8("actionComponentNumb_density"));
        actionEverything = new QAction(MainWindow);
        actionEverything->setObjectName(QString::fromUtf8("actionEverything"));
        actionFitToWindow = new QAction(MainWindow);
        actionTogglePlot = new QAction(MainWindow);
        actionPlotAdvanced = new QAction(MainWindow);
        actionAbout_SIMtoEXP = new QAction(MainWindow);
        actionUser_manual = new QAction(MainWindow);
        actionUser_manual->setObjectName(QString::fromUtf8("actionUser_manual"));
        actionLicense = new QAction(MainWindow);
        actionLicense->setObjectName(QString::fromUtf8("actionLicense"));
        actionScattering_lengths = new QAction(MainWindow);
        actionScattering_lengths->setObjectName(QString::fromUtf8("actionScattering_lengths"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        main_grid = new QGridLayout(centralwidget);
        main_grid->setObjectName(QString::fromUtf8("gridLayout"));
        tabWidget = new TabWidgetCloseable(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));

        num_densities_tab = new QWidget();
        num_densities_tab->setObjectName(QString::fromUtf8("num_densities_tab"));
        num_densities_grid = new QGridLayout(num_densities_tab);
        //create a scroll area and put the plot in it
        num_densities_plot = new QwtPlot;
        num_densities_plot->setFrameShape(QFrame::NoFrame);
        num_densities_plot->setCanvasBackground(QBrush(QColor(Qt::white)));
        num_densities_plot->setAxisAutoScale(QwtPlot::xBottom, false); //turn off autoscaling
        num_densities_plot->setAxisAutoScale(QwtPlot::yLeft, false); //turn off autoscaling
        //scrollzoomer settings
        num_densities_scroll = new ScrollZoomer(num_densities_plot->canvas());
        num_densities_scroll->setAxis(QwtPlot::xBottom, QwtPlot::yLeft);
        num_densities_scroll->setHScrollBarPosition(ScrollZoomer::AttachedToScale);
        num_densities_scroll->setVScrollBarPosition(ScrollZoomer::AttachedToScale);
        num_densities_grid->addWidget(num_densities_plot, 0, 0, 1, 1);
        tabWidget->addTab(num_densities_tab, QString());
        tabWidget->setTabEnabled(tabWidget->indexOf(num_densities_tab), false);

        e_densities_tab = new QWidget();
        e_densities_tab->setObjectName(QString::fromUtf8("e_densities_tab"));
        e_densities_grid = new QGridLayout(e_densities_tab);
        e_densities_grid->setObjectName(QString::fromUtf8("gridLayout_5"));
        e_densities_plot = new QwtPlot(e_densities_tab);
        e_densities_plot->setObjectName(QString::fromUtf8("e_densities_plot"));
        e_densities_plot->setFrameShape(QFrame::NoFrame);
        e_densities_plot->setCanvasBackground(QBrush(QColor(Qt::white)));
        //scrollzoomer settings
        e_densities_scroll = new ScrollZoomer(e_densities_plot->canvas());
        e_densities_scroll->setAxis(QwtPlot::xBottom, QwtPlot::yLeft);
        e_densities_scroll->setHScrollBarPosition(ScrollZoomer::AttachedToScale);
        e_densities_scroll->setVScrollBarPosition(ScrollZoomer::AttachedToScale);
        e_densities_grid->addWidget(e_densities_plot, 0, 0, 1, 1);
        tabWidget->addTab(e_densities_tab, QString());
        tabWidget->setTabEnabled(tabWidget->indexOf(e_densities_tab), false);

        neutron_SL_tab = new QWidget();
        neutron_SL_tab->setObjectName(QString::fromUtf8("neutron_SL_tab"));
        neutron_SL_grid = new QGridLayout(neutron_SL_tab);
        neutron_SL_grid->setObjectName(QString::fromUtf8("gridLayout_6"));
        neutron_SL_plot = new QwtPlot(neutron_SL_tab);
        neutron_SL_plot->setObjectName(QString::fromUtf8("neutron_SL_plot"));
        neutron_SL_plot->setFrameShape(QFrame::NoFrame);
        neutron_SL_plot->setCanvasBackground(QBrush(QColor(Qt::white)));
        //scrollzoomer settings
        neutron_SL_scroll = new ScrollZoomer(neutron_SL_plot->canvas());
        neutron_SL_scroll->setAxis(QwtPlot::xBottom, QwtPlot::yLeft);
        neutron_SL_scroll->setHScrollBarPosition(ScrollZoomer::AttachedToScale);
        neutron_SL_scroll->setVScrollBarPosition(ScrollZoomer::AttachedToScale);
        neutron_SL_grid->addWidget(neutron_SL_plot, 0, 0, 1, 1);
        tabWidget->addTab(neutron_SL_tab, QString());
        tabWidget->setTabEnabled(tabWidget->indexOf(neutron_SL_tab), false);

        xray_formfactors_tab = new QWidget();
        xray_formfactors_tab->setObjectName(QString::fromUtf8("xray_formfactors_tab"));
        xray_formfactors_grid = new QGridLayout(xray_formfactors_tab);
        xray_formfactors_grid->setObjectName(QString::fromUtf8("gridLayout_7"));
        xray_formfactors_plot = new QwtPlot(xray_formfactors_tab);
        xray_formfactors_plot->setObjectName(QString::fromUtf8("xray_formfactors_plot"));
        xray_formfactors_plot->setFrameShape(QFrame::NoFrame);
        xray_formfactors_plot->setCanvasBackground(QBrush(QColor(Qt::white)));
        xray_formfactors_scroll = new ScrollZoomer(xray_formfactors_plot->canvas());
        xray_formfactors_scroll->setAxis(QwtPlot::xBottom, QwtPlot::yLeft);
        xray_formfactors_scroll->setHScrollBarPosition(ScrollZoomer::AttachedToScale);
        xray_formfactors_scroll->setVScrollBarPosition(ScrollZoomer::AttachedToScale);
        xray_formfactors_grid->addWidget(xray_formfactors_plot, 0, 0, 1, 1);
        tabWidget->addTab(xray_formfactors_tab, QString());
        //don't show form factor tab until fourier transform calculated
        tabWidget->setTabEnabled(tabWidget->indexOf(xray_formfactors_tab), false);

        neutron_formfactors_tab = new QWidget();
        neutron_formfactors_tab->setObjectName(QString::fromUtf8("neutron_formfactors_tab"));
        neutron_formfactors_grid = new QGridLayout(neutron_formfactors_tab);
        neutron_formfactors_grid->setObjectName(QString::fromUtf8("gridLayout_8"));
        neutron_formfactors_plot = new QwtPlot(neutron_formfactors_tab);
        neutron_formfactors_plot->setObjectName(QString::fromUtf8("neutron_formfactors_plot"));
        neutron_formfactors_plot->setFrameShape(QFrame::NoFrame);
        neutron_formfactors_plot->setCanvasBackground(QBrush(QColor(Qt::white)));
        neutron_formfactors_scroll = new ScrollZoomer(neutron_formfactors_plot->canvas());
        neutron_formfactors_scroll->setAxis(QwtPlot::xBottom, QwtPlot::yLeft);
        neutron_formfactors_scroll->setHScrollBarPosition(ScrollZoomer::AttachedToScale);
        neutron_formfactors_scroll->setVScrollBarPosition(ScrollZoomer::AttachedToScale);
        neutron_formfactors_grid->addWidget(neutron_formfactors_plot, 0, 0, 1, 1);
        tabWidget->addTab(neutron_formfactors_tab, QString());
        tabWidget->setTabEnabled(tabWidget->indexOf(neutron_formfactors_tab), false);

        vol_probs_tab = new QWidget();
        vol_probs_tab->setObjectName(QString::fromUtf8("vol_probs_tab"));
        vol_probs_grid = new QGridLayout(vol_probs_tab);
        vol_probs_grid->setObjectName(QString::fromUtf8("gridLayout_10"));
        vol_probs_plot = new QwtPlot(vol_probs_tab);
        vol_probs_plot->setObjectName(QString::fromUtf8("vol_probs_plot"));
        vol_probs_plot->setFrameShape(QFrame::NoFrame);
        vol_probs_plot->setCanvasBackground(QBrush(QColor(Qt::white)));
        vol_probs_scroll = new ScrollZoomer(vol_probs_plot->canvas());
        vol_probs_scroll->setAxis(QwtPlot::xBottom, QwtPlot::yLeft);
        vol_probs_scroll->setHScrollBarPosition(ScrollZoomer::AttachedToScale);
        vol_probs_scroll->setVScrollBarPosition(ScrollZoomer::AttachedToScale);
        vol_probs_grid->addWidget(vol_probs_plot, 0, 0, 1, 1);
        tabWidget->addTab(vol_probs_tab, QString());
        tabWidget->setTabEnabled(tabWidget->indexOf(vol_probs_tab), false);

        main_grid->addWidget(tabWidget, 0, 0, 1, 2);

        /*
         * Margins region
         */

        margins = new QGroupBox("Margins", centralwidget);
        margins->setAlignment(Qt::AlignLeft);
        margins_horizontalLayout = new QHBoxLayout(margins);

        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);

        left_label = new QLabel(centralwidget);
        left_label->setObjectName(QString::fromUtf8("left_label"));
        left_label->setFont(font);

        margins_horizontalLayout->addWidget(left_label);

        left_margin_lineEdit = new QLineEdit(centralwidget);
        left_margin_lineEdit->setObjectName(QString::fromUtf8("left_margin_lineEdit"));
        left_margin_lineEdit->setReadOnly(true);

        margins_horizontalLayout->addWidget(left_margin_lineEdit);

        right_label = new QLabel(centralwidget);
        right_label->setObjectName(QString::fromUtf8("label_26"));
        right_label->setFont(font);

        margins_horizontalLayout->addWidget(right_label);

        right_margin_lineEdit = new QLineEdit(centralwidget);
        right_margin_lineEdit->setObjectName(QString::fromUtf8("right_margin_lineEdit"));
        right_margin_lineEdit->setReadOnly(true);

        margins_horizontalLayout->addWidget(right_margin_lineEdit);

        //add the group box to the MainWindow grid
        main_grid->addWidget(margins, 1, 0);


        /*
         * Simulation form factor region
         */

        simFormFactors = new QGroupBox("Simulation form factor analysis",centralwidget);
        simGrid = new QGridLayout(simFormFactors);
        fourierLayout = new QHBoxLayout;

        fourier_button = new QPushButton(simFormFactors);
        fourierLayout->addWidget(fourier_button);

        sym_checkBox = new QCheckBox(simFormFactors);
        fourierLayout->addWidget(sym_checkBox);

        defaults_button = new QPushButton(simFormFactors);
        fourierLayout->addWidget(defaults_button);

        //add horizontal box at top of grid
        simGrid->addLayout(fourierLayout, 0, 0, 1, -1);

        q_int_label = new QLabel(simFormFactors);
        q_int_label->setObjectName(QString::fromUtf8("q_int_label"));
        QFont font2;
        font2.setBold(true);
        font2.setWeight(75);
        q_int_label->setFont(font2);

        simGrid->addWidget(q_int_label, 1, 0);

        low_label = new QLabel(simFormFactors);
        low_label->setObjectName(QString::fromUtf8("label_6"));
        low_label->setFont(font2);
        low_label->setAlignment(Qt::AlignCenter);

        simGrid->addWidget(low_label, 1, 1);

        high_label = new QLabel(simFormFactors);
        high_label->setObjectName(QString::fromUtf8("label_7"));
        high_label->setFont(font2);
        high_label->setAlignment(Qt::AlignCenter);

        simGrid->addWidget(high_label, 1, 2);

        step_label = new QLabel(simFormFactors);
        step_label->setObjectName(QString::fromUtf8("label_8"));
        step_label->setFont(font2);
        step_label->setAlignment(Qt::AlignCenter);

        simGrid->addWidget(step_label, 1, 3);

        xray_int_label = new QLabel(simFormFactors);
        xray_int_label->setObjectName(QString::fromUtf8("label_4"));
        xray_int_label->setFont(font2);

        simGrid->addWidget(xray_int_label, 2, 0);

        xray_qlow_lineEdit = new QLineEdit(simFormFactors);
        xray_qlow_lineEdit->setObjectName(QString::fromUtf8("xray_qlow_lineEdit"));
        xray_qlow_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(xray_qlow_lineEdit, 2, 1);

        xray_qhigh_lineEdit = new QLineEdit(simFormFactors);
        xray_qhigh_lineEdit->setObjectName(QString::fromUtf8("xray_qhigh_lineEdit"));
        xray_qhigh_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(xray_qhigh_lineEdit, 2, 2);

        xray_qstep_lineEdit = new QLineEdit(simFormFactors);
        xray_qstep_lineEdit->setObjectName(QString::fromUtf8("xray_qstep_lineEdit"));
        xray_qstep_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(xray_qstep_lineEdit, 2, 3);

        neutron_int_label = new QLabel(simFormFactors);
        neutron_int_label->setObjectName(QString::fromUtf8("label_5"));
        neutron_int_label->setFont(font2);

        simGrid->addWidget(neutron_int_label, 3, 0);

        neut_qlow_lineEdit = new QLineEdit(simFormFactors);
        neut_qlow_lineEdit->setObjectName(QString::fromUtf8("neut_qlow_lineEdit"));
        neut_qlow_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(neut_qlow_lineEdit, 3, 1);

        neut_qhigh_lineEdit = new QLineEdit(simFormFactors);
        neut_qhigh_lineEdit->setObjectName(QString::fromUtf8("neut_qhigh_lineEdit"));
        neut_qhigh_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(neut_qhigh_lineEdit, 3, 2);

        neut_qstep_lineEdit = new QLineEdit(simFormFactors);
        neut_qstep_lineEdit->setObjectName(QString::fromUtf8("neut_qstep_lineEdit"));
        neut_qstep_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(neut_qstep_lineEdit, 3, 3);

        solv_ed_label = new QLabel(simFormFactors);
        solv_ed_label->setObjectName(QString::fromUtf8("solv_ed_label"));
        QFont font1;
        font1.setPointSize(9);
        font1.setBold(true);
        font1.setWeight(75);
        solv_ed_label->setFont(font1);

        simGrid->addWidget(solv_ed_label, 4, 0);

        solv_ed_lineEdit = new QLineEdit(simFormFactors);
        solv_ed_lineEdit->setObjectName(QString::fromUtf8("solv_ed_lineEdit"));
        solv_ed_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(solv_ed_lineEdit, 4, 1); //in cell (4,1) spanning 2 columns

        solv_nsld_label = new QLabel(simFormFactors);
        solv_nsld_label->setObjectName(QString::fromUtf8("label_2"));
        solv_nsld_label->setFont(font1);

        simGrid->addWidget(solv_nsld_label, 4, 2);

        solv_nsld_lineEdit = new QLineEdit(simFormFactors);
        solv_nsld_lineEdit->setObjectName(QString::fromUtf8("solv_nsld_lineEdit"));
        solv_nsld_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);

        simGrid->addWidget(solv_nsld_lineEdit, 4, 3); //in cell (5,1) spanning 2 rows

        //set all minimum horizontal sizes for lineEdits to the longest widget, which at the moment is 'nsld label'
        int min_width = solv_nsld_label->width();
        xray_qlow_lineEdit->setMinimumWidth(min_width);
        xray_qhigh_lineEdit->setMinimumWidth(min_width);
        xray_qstep_lineEdit->setMinimumWidth(min_width);
        neut_qlow_lineEdit->setMinimumWidth(min_width);
        neut_qhigh_lineEdit->setMinimumWidth(min_width);
        neut_qstep_lineEdit->setMinimumWidth(min_width);
        solv_ed_lineEdit->setMinimumWidth(min_width);
        solv_nsld_lineEdit->setMinimumWidth(min_width);


        //add the group box to the main window grid
        main_grid->addWidget(simFormFactors, 2, 0, 5, 1);

        //end of simulation form factor region


        /*
         * Experimental form factor region
         */

        expFormFactors = new QGroupBox("Experimental form factors", centralwidget);
        expGrid = new QGridLayout(expFormFactors);

        xray_sample_label = new QLabel(expFormFactors);
        xray_sample_label->setFont(font2);
        xray_sample_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_sample_label, 0, 0);

        xray_scale_button = new QPushButton(expFormFactors);
        expGrid->addWidget(xray_scale_button, 1, 0);

        xray_chi_label = new QLabel(expFormFactors);
        QFont font3;
        font3.setPointSize(11);
        xray_chi_label->setFont(font3);
        xray_chi_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_chi_label, 2, 0);

        xray_sam1_label = new QLabel(expFormFactors);
        xray_sam1_label->setFont(font2);
        xray_sam1_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_sam1_label, 0, 1);

        xray_scale_sam1_lineEdit = new QLineEdit(expFormFactors);
        xray_scale_sam1_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_scale_sam1_lineEdit, 1, 1);

        xray_chi_sam1_lineEdit = new QLineEdit(expFormFactors);
        xray_chi_sam1_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_chi_sam1_lineEdit, 2, 1);

        xray_sam2_label = new QLabel(expFormFactors);
        xray_sam2_label->setFont(font2);
        xray_sam2_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_sam2_label, 0, 2);

        xray_scale_sam2_lineEdit = new QLineEdit(expFormFactors);
        xray_scale_sam2_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_scale_sam2_lineEdit, 1, 2);

        xray_chi_sam2_lineEdit = new QLineEdit(expFormFactors);
        xray_chi_sam2_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_chi_sam2_lineEdit, 2, 2);

        xray_sam3_label = new QLabel(expFormFactors);
        xray_sam3_label->setFont(font2);
        xray_sam3_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_sam3_label, 0, 3);

        xray_scale_sam3_lineEdit = new QLineEdit(expFormFactors);
        xray_scale_sam3_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_scale_sam3_lineEdit, 1, 3);

        xray_chi_sam3_lineEdit = new QLineEdit(expFormFactors);
        xray_chi_sam3_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_chi_sam3_lineEdit, 2, 3);

        xray_sam4_label = new QLabel(expFormFactors);
        xray_sam4_label->setFont(font2);
        xray_sam4_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_sam4_label, 0, 4);

        xray_scale_sam4_lineEdit = new QLineEdit(expFormFactors);
        xray_scale_sam4_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_scale_sam4_lineEdit, 1, 4);

        xray_chi_sam4_lineEdit = new QLineEdit(expFormFactors);
        xray_chi_sam4_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_chi_sam4_lineEdit, 2, 4);

        xray_sam5_label = new QLabel(expFormFactors);
        xray_sam5_label->setFont(font2);
        xray_sam5_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(xray_sam5_label, 0, 5);

        xray_scale_sam5_lineEdit = new QLineEdit(expFormFactors);
        xray_scale_sam5_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_scale_sam5_lineEdit, 1, 5);

        xray_chi_sam5_lineEdit = new QLineEdit(expFormFactors);
        xray_chi_sam5_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(xray_chi_sam5_lineEdit, 2, 5);

        neut_sample_label = new QLabel(expFormFactors);
        neut_sample_label->setFont(font2);
        neut_sample_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_sample_label, 3, 0);

        neut_scale_button = new QPushButton(expFormFactors);
        expGrid->addWidget(neut_scale_button, 4, 0);

        neut_chi_label = new QLabel(expFormFactors);
        neut_chi_label->setFont(font3);
        neut_chi_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_chi_label, 5, 0);

        neut_sam1_label = new QLabel(expFormFactors);
        neut_sam1_label->setFont(font2);
        neut_sam1_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_sam1_label, 3, 1);

        neut_scale_sam1_lineEdit = new QLineEdit(expFormFactors);
        neut_scale_sam1_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_scale_sam1_lineEdit, 4, 1);

        neut_chi_sam1_lineEdit = new QLineEdit(expFormFactors);
        neut_chi_sam1_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_chi_sam1_lineEdit, 5, 1);

        neut_sam2_label = new QLabel(expFormFactors);
        neut_sam2_label->setFont(font2);
        neut_sam2_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_sam2_label, 3, 2);

        neut_scale_sam2_lineEdit = new QLineEdit(expFormFactors);
        neut_scale_sam2_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_scale_sam2_lineEdit, 4, 2);

        neut_chi_sam2_lineEdit = new QLineEdit(expFormFactors);
        neut_chi_sam2_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_chi_sam2_lineEdit, 5, 2);

        neut_sam3_label = new QLabel(expFormFactors);
        neut_sam3_label->setFont(font2);
        neut_sam3_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_sam3_label, 3, 3);

        neut_scale_sam3_lineEdit = new QLineEdit(expFormFactors);
        neut_scale_sam3_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_scale_sam3_lineEdit, 4, 3);

        neut_chi_sam3_lineEdit = new QLineEdit(expFormFactors);
        neut_chi_sam3_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_chi_sam3_lineEdit, 5, 3);

        neut_sam4_label = new QLabel(expFormFactors);
        neut_sam4_label->setFont(font2);
        neut_sam4_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_sam4_label, 3, 4);

        neut_scale_sam4_lineEdit = new QLineEdit(expFormFactors);
        neut_scale_sam4_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_scale_sam4_lineEdit, 4, 4);

        neut_chi_sam4_lineEdit = new QLineEdit(expFormFactors);
        neut_chi_sam4_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_chi_sam4_lineEdit, 5, 4);

        neut_sam5_label = new QLabel(expFormFactors);
        neut_sam5_label->setFont(font2);
        neut_sam5_label->setAlignment(Qt::AlignCenter);
        expGrid->addWidget(neut_sam5_label, 3, 5);

        neut_scale_sam5_lineEdit = new QLineEdit(expFormFactors);
        neut_scale_sam5_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_scale_sam5_lineEdit, 4, 5);

        neut_chi_sam5_lineEdit = new QLineEdit(expFormFactors);
        neut_chi_sam5_lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        expGrid->addWidget(neut_chi_sam5_lineEdit, 5, 5);

        //finally, add the QGroupBox to the mainwindow grid
        main_grid->addWidget(expFormFactors, 8, 0, 6, 1);

        /*
         * Component region
         */

        components = new QGroupBox("Components", centralwidget);
        componentGrid = new QGridLayout(components);
        volumeLayout = new QHBoxLayout;

        calc_volume_button = new QPushButton(components);
        calc_volume_button->setObjectName(QString::fromUtf8("calc_volume_button"));
        volumeLayout->addWidget(calc_volume_button);

        rms_label = new QLabel(components);
        rms_label->setObjectName(QString::fromUtf8("rms_label"));
        rms_label->setFont(font);
        volumeLayout->addWidget(rms_label);

        vol_rms_lineEdit = new QLineEdit(components);
        vol_rms_lineEdit->setObjectName(QString::fromUtf8("vol_rms_lineEdit"));
        vol_rms_lineEdit->setReadOnly(true);
        volumeLayout->addWidget(vol_rms_lineEdit);

        //add the horizontal layout at the top of the component grid
        componentGrid->addLayout(volumeLayout, 0, 0, 1, -1); //fill to the right

        //create and add all of the labels
        for(int i = 0; i < COMPONENT_COLUMNS; i++) {

            cmp_labels.append(new QLabel(components));
            cmp_labels[i]->setFont(font2);
            cmp_labels[i]->setAlignment(Qt::AlignCenter);
            componentGrid->addWidget(cmp_labels[i], 1, i);
        }

        //create and add the component line edits
        for(int j = 0; j < cmp_edits.size(); j++) {
			for(int i = 0; i < COMPONENT_ROWS; i++) {

				cmp_edits[j]->append(new QLineEdit(components));
				(*cmp_edits[j])[i]->setAlignment(Qt::AlignRight);
				(*cmp_edits[j])[i]->setReadOnly(true);

				//for the first row, make minimum a little bigger
				int cur_width = (*cmp_edits[j])[i]->width();
				if(j == 0)
					(*cmp_edits[j])[i]->setMinimumWidth(cur_width);
				else
					(*cmp_edits[j])[i]->setMinimumWidth(cur_width * 0.8);

				componentGrid->addWidget((*cmp_edits[j])[i], i+2, j); //start at row number 2, 2 columns wide
			}
        }

        //have to force the spacing
        componentGrid->setVerticalSpacing(10);

        //add the group box to the main window grid
        main_grid->addWidget(components, 1, 1, -1, -1); //only widget in the right column

        //end of components section

        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 981, 19));
        menu_File = new QMenu(menubar);
        menu_File->setObjectName(QString::fromUtf8("menu_File"));
        menuOpen = new QMenu(menu_File);
        menuOpen->setObjectName(QString::fromUtf8("menuOpen"));
        menuSimulation_data = new QMenu(menuOpen);
        menuSimulation_data->setObjectName(QString::fromUtf8("menuSimulation_data"));
        menuStructureFactor_data = new QMenu(menuOpen);
        menuStructureFactor_data->setObjectName(QString::fromUtf8("menuStructureFactor_data"));
		menuDelete = new QMenu(menu_File);
		menuDelete->setObjectName(QString::fromUtf8("menuDelete"));
		menuXrayDelete = new QMenu(menuDelete);
		menuXrayDelete->setObjectName(QString::fromUtf8("menuXrayDelete"));
        menuNeutronDelete = new QMenu(menuDelete);
        menuNeutronDelete->setObjectName(QString::fromUtf8("menuNeutronDelete"));
        menu_Tools = new QMenu(menubar);
        menu_Tools->setObjectName(QString::fromUtf8("menu_Tools"));
        menuE_xport = new QMenu(menu_Tools);
        menuE_xport->setObjectName(QString::fromUtf8("menuE_xport"));
        menuExpNumberDensity = new QMenu(menuE_xport);
        menuExpNumberDensity->setObjectName(QString::fromUtf8("menuExpNumberDensity"));
        menuExpElectDensity = new QMenu(menuE_xport);
        menuExpElectDensity->setObjectName(QString::fromUtf8("menuExpElectDensity"));
        menuExpNSLDensity = new QMenu(menuE_xport);
        menuExpNSLDensity->setObjectName(QString::fromUtf8("menuExpNSLDensity"));
        menu_Window = new QMenu(menubar);
        menu_Window->setObjectName(QString::fromUtf8("menu_Plot"));
        menu_Help = new QMenu(menubar);
        menu_Help->setObjectName(QString::fromUtf8("menu_Help"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menu_File->menuAction());
        menubar->addAction(menu_Tools->menuAction());
        menubar->addAction(menu_Window->menuAction());
        menubar->addAction(menu_Help->menuAction());
        menu_File->addAction(menuOpen->menuAction());
        menu_File->addAction(menuDelete->menuAction());
        menu_File->addAction(actionExit);
        menuOpen->addAction(menuSimulation_data->menuAction());
        menuOpen->addAction(menuStructureFactor_data->menuAction());
        menuOpen->addAction(actionElectron_density_profile);
        menuOpen->addAction(actionNeutron_Scattering_Length_Density);
        menuOpen->addAction(actionComponent_file);
        menuSimulation_data->addAction(actionSIMtoEXP_format);
        menuSimulation_data->addAction(actionTrajFiles);
        menuStructureFactor_data->addAction(actionX_ray);
        menuStructureFactor_data->addAction(actionNeutron);
		menuDelete->addAction(actionDeleteSim);
		menuDelete->addAction(menuXrayDelete->menuAction());
		menuDelete->addAction(menuNeutronDelete->menuAction());
		menuDelete->addAction(actionDeleteED);
		menuDelete->addAction(actionDeleteNSLD);
        menuDelete->addAction(actionDeleteComponents);
		menuXrayDelete->addAction(actionDeleteXray1);
		menuXrayDelete->addAction(actionDeleteXray2);
		menuXrayDelete->addAction(actionDeleteXray3);
		menuXrayDelete->addAction(actionDeleteXray4);
		menuXrayDelete->addAction(actionDeleteXray5);
		menuNeutronDelete->addAction(actionDeleteNeutron1);
		menuNeutronDelete->addAction(actionDeleteNeutron2);
		menuNeutronDelete->addAction(actionDeleteNeutron3);
		menuNeutronDelete->addAction(actionDeleteNeutron4);
		menuNeutronDelete->addAction(actionDeleteNeutron5);
        menu_Tools->addAction(actionScattering_lengths);
        menu_Tools->addAction(action_Atomic_form_factors);
        menu_Tools->addAction(menuE_xport->menuAction());
        menu_Tools->addAction(actionSi_mulation_specifics);
        menu_Tools->addAction(action_Analysis);
        menuE_xport->addAction(actionEverything);
        menuE_xport->addAction(menuExpNumberDensity->menuAction());
        menuE_xport->addAction(menuExpElectDensity->menuAction());
        menuE_xport->addAction(menuExpNSLDensity->menuAction());
        menuE_xport->addAction(action_X_ray_form_factors);
        menuE_xport->addAction(actionNeutron_form_factors);
        menuE_xport->addAction(actionVolumetric_fit);
        menuExpNumberDensity->addAction(actionElementalNumb_density);
        menuExpNumberDensity->addAction(actionParticleNumb_density);
        menuExpNumberDensity->addAction(actionComponentNumb_density);
        menuExpElectDensity->addAction(actionElementalElectron_density);
        menuExpElectDensity->addAction(actionComponentElectron_density);
        menuExpNSLDensity->addAction(actionElementalNeutron_SL_density);
        menuExpNSLDensity->addAction(actionComponentNeutron_SL_density);
        menu_Window->addAction(actionTogglePlot);
        menu_Window->addAction(actionFitToWindow);
        menu_Window->addAction(actionPlotAdvanced);
        menu_Help->addAction(actionAbout_SIMtoEXP);
        menu_Help->addAction(actionUser_manual);
        menu_Help->addAction(actionLicense);

        retranslateUi(MainWindow);

        //'exit' option
        QObject::connect(actionExit, SIGNAL(triggered(bool)), MainWindow, SLOT(close()));

        tabWidget->setCurrentIndex(tabWidget->indexOf(num_densities_tab)); //start at the number density tab
        tabWidget->setTabsClosable(true);

        //hack to hide close buttons for first six tabs
        tabWidget->hideCloseButton(tabWidget->indexOf(e_densities_tab));
        tabWidget->hideCloseButton(tabWidget->indexOf(neutron_SL_tab));
        tabWidget->hideCloseButton(tabWidget->indexOf(xray_formfactors_tab));
        tabWidget->hideCloseButton(tabWidget->indexOf(neutron_formfactors_tab));
        tabWidget->hideCloseButton(tabWidget->indexOf(num_densities_tab));
        tabWidget->hideCloseButton(tabWidget->indexOf(vol_probs_tab));

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

#if QT_VERSION >= 0x050000
    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "SIMulation to EXPeriment", 0));
        actionExit->setText(QApplication::translate("MainWindow", "E&xit", 0));
        actionExit->setShortcut(QApplication::translate("MainWindow", "Ctrl+X", 0));
        actionSIMtoEXP_format->setText(QApplication::translate("MainWindow", "&SIMtoEXP format", 0));
        actionTrajFiles->setText(QApplication::translate("MainWindow", "&Simulation trajectory file", 0));
        actionX_ray->setText(QApplication::translate("MainWindow", "&X-ray", 0));
        actionNeutron->setText(QApplication::translate("MainWindow", "&Neutron", 0));
        actionDeleteSim->setText(QApplication::translate("MainWindow", "&Simulation data", 0));
        actionDeleteED->setText(QApplication::translate("MainWindow", "&Electron density profile", 0));
        actionDeleteNSLD->setText(QApplication::translate("MainWindow", "Neutron SL density profile", 0));
        actionDeleteComponents->setText(QApplication::translate("MainWindow", "&Components", 0));
        actionDeleteXray1->setText(QApplication::translate("MainWindow", "Sample 1", 0));
        actionDeleteXray1->setVisible(false); //default to hidden, only show when loaded later
        actionDeleteXray2->setText(QApplication::translate("MainWindow", "Sample 2", 0));
        actionDeleteXray2->setVisible(false);
        actionDeleteXray3->setText(QApplication::translate("MainWindow", "Sample 3", 0));
        actionDeleteXray3->setVisible(false);
        actionDeleteXray4->setText(QApplication::translate("MainWindow", "Sample 4", 0));
        actionDeleteXray4->setVisible(false);
        actionDeleteXray5->setText(QApplication::translate("MainWindow", "Sample 5", 0));
        actionDeleteXray5->setVisible(false);
        actionDeleteNeutron1->setText(QApplication::translate("MainWindow", "Sample 1", 0));
        actionDeleteNeutron1->setVisible(false); //default to hidden, only show when loaded later
        actionDeleteNeutron2->setText(QApplication::translate("MainWindow", "Sample 2", 0));
        actionDeleteNeutron2->setVisible(false);
        actionDeleteNeutron3->setText(QApplication::translate("MainWindow", "Sample 3", 0));
        actionDeleteNeutron3->setVisible(false);
        actionDeleteNeutron4->setText(QApplication::translate("MainWindow", "Sample 4", 0));
        actionDeleteNeutron4->setVisible(false);
        actionDeleteNeutron5->setText(QApplication::translate("MainWindow", "Sample 5", 0));
        actionDeleteNeutron5->setVisible(false);
        actionElectron_density_profile->setText(QApplication::translate("MainWindow", "&Electron density profile", 0));
        actionNeutron_Scattering_Length_Density->setText(QApplication::translate("MainWindow", "&Neutron scattering length density", 0));
        actionComponent_file->setText(QApplication::translate("MainWindow", "&Component file", 0));
        action_Atomic_form_factors->setText(QApplication::translate("MainWindow", "&Atomic form factors", 0));
        actionSi_mulation_specifics->setText(QApplication::translate("MainWindow", "Si&mulation details", 0));
        action_Analysis->setText(QApplication::translate("MainWindow", "&Analysis", 0));
        actionEverything->setText(QApplication::translate("MainWindow", "Every&thing", 0));
        actionElementalNumb_density->setText(QApplication::translate("MainWindow", "Elemental", 0));
        actionParticleNumb_density->setText(QApplication::translate("MainWindow", "Particles", 0));
        actionComponentNumb_density->setText(QApplication::translate("MainWindow", "Components", 0));
        actionElementalElectron_density->setText(QApplication::translate("MainWindow", "&Elemental", 0));
        actionComponentElectron_density->setText(QApplication::translate("MainWindow", "&Component", 0));
        actionElementalNeutron_SL_density->setText(QApplication::translate("MainWindow", "Elemental", 0));
        actionComponentNeutron_SL_density->setText(QApplication::translate("MainWindow", "Component", 0));
        action_X_ray_form_factors->setText(QApplication::translate("MainWindow", "&X-ray form factors", 0));
        actionNeutron_form_factors->setText(QApplication::translate("MainWindow", "&Neutron form factors", 0));
        actionVolumetric_fit->setText(QApplication::translate("MainWindow", "&Volumetric fit", 0));
        actionFitToWindow->setText(QApplication::translate("MainWindow", "&Fit plot to window", 0));
        actionFitToWindow->setShortcut(QApplication::translate("MainWindow", "Ctrl+A", 0));
        actionTogglePlot->setText(QApplication::translate("MainWindow", "&Toggle full screen plot", 0));
        actionTogglePlot->setShortcut(QApplication::translate("MainWindow", "Ctrl+T", 0));
        actionPlotAdvanced->setText(QApplication::translate("MainWindow", "&Advanced", 0));
        actionAbout_SIMtoEXP->setText(QApplication::translate("MainWindow", "About SIMtoEXP", 0));
        actionUser_manual->setText(QApplication::translate("MainWindow", "User manual", 0));
        actionLicense->setText(QApplication::translate("MainWindow", "License", 0));
        actionScattering_lengths->setText(QApplication::translate("MainWindow", "&Scattering lengths", 0));
        tabWidget->setTabText(tabWidget->indexOf(e_densities_tab), QApplication::translate("MainWindow", "Electron Densities", 0));
        tabWidget->setTabText(tabWidget->indexOf(neutron_SL_tab), QApplication::translate("MainWindow", "Neutron SL Densities", 0));
        tabWidget->setTabText(tabWidget->indexOf(xray_formfactors_tab), QApplication::translate("MainWindow", "X-ray Form Factors", 0));
        tabWidget->setTabText(tabWidget->indexOf(neutron_formfactors_tab), QApplication::translate("MainWindow", "Neutron Form Factors", 0));
        tabWidget->setTabText(tabWidget->indexOf(num_densities_tab), QApplication::translate("MainWindow", "Number Densities", 0));
        tabWidget->setTabText(tabWidget->indexOf(vol_probs_tab), QApplication::translate("MainWindow", "Volume Probabilities", 0));

        left_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Left:</span></p></body></html>", 0));
        right_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Right:</span></p></body></html>", 0));
        calc_volume_button->setText(QApplication::translate("MainWindow", "Calculate volumes", 0));
        rms_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">rms</span>:</p></body></html>", 0));
        fourier_button->setText(QApplication::translate("MainWindow", "Fourier Transform", 0));
        sym_checkBox->setText(QApplication::translate("MainWindow", "Symmetrized", 0));
        defaults_button->setText(QApplication::translate("MainWindow", "Reset defaults", 0));
        solv_ed_label->setText(QApplication::translate("MainWindow", "Solvent ED", 0));
        solv_ed_lineEdit->setText(QApplication::translate("MainWindow", "0.333", 0));
        solv_nsld_label->setText(QApplication::translate("MainWindow", "Solvent NSLD", 0));
        solv_nsld_lineEdit->setText(QApplication::translate("MainWindow", "6.38E-6", 0));
        q_int_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">q Interval:</span></p></body></html>", 0));
        low_label->setText(QApplication::translate("MainWindow", "Low", 0));
        high_label->setText(QApplication::translate("MainWindow", "High", 0));
        step_label->setText(QApplication::translate("MainWindow", "Step", 0));
        xray_int_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">X-ray</span></p></body></html>", 0));
        xray_qlow_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        xray_qhigh_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        xray_qstep_lineEdit->setText(QApplication::translate("MainWindow", "0.001", 0));
        neutron_int_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#800000;\">Neutron</span></p></body></html>", 0));
        neut_qlow_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        neut_qhigh_lineEdit->setText(QApplication::translate("MainWindow", "0.4", 0));
        neut_qstep_lineEdit->setText(QApplication::translate("MainWindow", "0.0025", 0));

        cmp_labels[CMP_ID_INDEX]->setText(QApplication::translate("MainWindow", "ID", 0));
        cmp_labels[CMP_NATOMS_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p># Atom</p></body></html>", 0));
        cmp_labels[CMP_ATOMS_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p>Atom/grp</p></body></html>", 0));
        cmp_labels[CMP_NGROUPS_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p># grps</p></body></html>", 0));
        cmp_labels[CMP_NELEC_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p># e<span style=\" vertical-align:super;\">-</span>/grp</p></body></html>", 0));
        cmp_labels[CMP_NSLD_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p>SL<span style=\" vertical-align:sub;\">n</span>/grp</p></body></html>", 0));
        cmp_labels[CMP_VOLUME_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">grp</span></p></body></html>", 0));

        //ids have nothing in them
        for(int i = 0; i < id_edits.size(); i++)
            id_edits[i]->setText(QApplication::translate("MainWindow", "", 0));

        //loop through rest of line edits to set text
        for(int i = 1; i < cmp_edits.size(); i++)
            for(int j = 0; j < COMPONENT_ROWS; j++)
                (*cmp_edits[i])[j]->setText(QApplication::translate("MainWindow", "0.0", 0));

        xray_sample_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">X-ray</span></p></body></html>", 0));
        xray_scale_button->setText(QApplication::translate("MainWindow", "Scale", 0));
        xray_chi_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>\317\207<span style=\" vertical-align:super;\">2</span></p></body></html>", 0));
        xray_sam1_label->setText(QApplication::translate("MainWindow", "1", 0));
        xray_scale_sam1_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        xray_chi_sam1_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        xray_sam2_label->setText(QApplication::translate("MainWindow", "2", 0));
        xray_scale_sam2_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        xray_chi_sam2_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        xray_sam3_label->setText(QApplication::translate("MainWindow", "3", 0));
        xray_scale_sam3_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        xray_chi_sam3_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        xray_sam4_label->setText(QApplication::translate("MainWindow", "4", 0));
        xray_scale_sam4_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        xray_chi_sam4_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        xray_sam5_label->setText(QApplication::translate("MainWindow", "5", 0));
        xray_scale_sam5_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        xray_chi_sam5_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        neut_sample_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#800000;\">Neutron</span></p></body></html>", 0));
        neut_scale_button->setText(QApplication::translate("MainWindow", "Scale", 0));
        neut_chi_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>\317\207<span style=\" vertical-align:super;\">2</span></p></body></html>", 0));
        neut_sam1_label->setText(QApplication::translate("MainWindow", "", 0));
        neut_scale_sam1_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        neut_chi_sam1_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        neut_sam2_label->setText(QApplication::translate("MainWindow", "", 0));
        neut_scale_sam2_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        neut_chi_sam2_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        neut_sam3_label->setText(QApplication::translate("MainWindow", "", 0));
        neut_scale_sam3_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        neut_chi_sam3_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        neut_sam4_label->setText(QApplication::translate("MainWindow", "", 0));
        neut_scale_sam4_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        neut_chi_sam4_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        neut_sam5_label->setText(QApplication::translate("MainWindow", "", 0));
        neut_scale_sam5_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0));
        neut_chi_sam5_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0));
        menu_File->setTitle(QApplication::translate("MainWindow", "&File", 0));
        menuOpen->setTitle(QApplication::translate("MainWindow", "&Open", 0));
        menuSimulation_data->setTitle(QApplication::translate("MainWindow", "&Simulation data", 0));
        menuStructureFactor_data->setTitle(QApplication::translate("MainWindow", "S&tructure factors", 0));
        menuDelete->setTitle(QApplication::translate("MainWindow", "&Delete", 0));
        menuXrayDelete->setTitle(QApplication::translate("MainWindow", "&X-ray", 0));
        menuNeutronDelete->setTitle(QApplication::translate("MainWindow", "&Neutron", 0));
        menu_Tools->setTitle(QApplication::translate("MainWindow", "&Tools", 0));
        menuE_xport->setTitle(QApplication::translate("MainWindow", "E&xport", 0));
        menuExpNumberDensity->setTitle(QApplication::translate("MainWindow", "&Number Density", 0));
        menuExpElectDensity->setTitle(QApplication::translate("MainWindow", "&Electron Density", 0));
        menuExpNSLDensity->setTitle(QApplication::translate("MainWindow", "Neutron &SL Density", 0));
        menu_Window->setTitle(QApplication::translate("MainWindow", "&Window", 0));
        menu_Help->setTitle(QApplication::translate("MainWindow", "&Help", 0));
    } // retranslateUi
#else
    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "SIMulation to EXPeriment", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("MainWindow", "E&xit", 0, QApplication::UnicodeUTF8));
        actionExit->setShortcut(QApplication::translate("MainWindow", "Ctrl+X", 0, QApplication::UnicodeUTF8));
        actionSIMtoEXP_format->setText(QApplication::translate("MainWindow", "&SIMtoEXP format", 0, QApplication::UnicodeUTF8));
        actionTrajFiles->setText(QApplication::translate("MainWindow", "&Simulation trajectory file", 0, QApplication::UnicodeUTF8));
        actionX_ray->setText(QApplication::translate("MainWindow", "&X-ray", 0, QApplication::UnicodeUTF8));
        actionNeutron->setText(QApplication::translate("MainWindow", "&Neutron", 0, QApplication::UnicodeUTF8));
        actionDeleteSim->setText(QApplication::translate("MainWindow", "&Simulation data", 0, QApplication::UnicodeUTF8));
        actionDeleteED->setText(QApplication::translate("MainWindow", "&Electron density profile", 0, QApplication::UnicodeUTF8));
        actionDeleteNSLD->setText(QApplication::translate("MainWindow", "Neutron SL density profile", 0, QApplication::UnicodeUTF8));
        actionDeleteComponents->setText(QApplication::translate("MainWindow", "&Components", 0, QApplication::UnicodeUTF8));
        actionDeleteXray1->setText(QApplication::translate("MainWindow", "Sample 1", 0, QApplication::UnicodeUTF8));
        actionDeleteXray1->setVisible(false); //default to hidden, only show when loaded later
        actionDeleteXray2->setText(QApplication::translate("MainWindow", "Sample 2", 0, QApplication::UnicodeUTF8));
        actionDeleteXray2->setVisible(false);
        actionDeleteXray3->setText(QApplication::translate("MainWindow", "Sample 3", 0, QApplication::UnicodeUTF8));
        actionDeleteXray3->setVisible(false);
        actionDeleteXray4->setText(QApplication::translate("MainWindow", "Sample 4", 0, QApplication::UnicodeUTF8));
        actionDeleteXray4->setVisible(false);
        actionDeleteXray5->setText(QApplication::translate("MainWindow", "Sample 5", 0, QApplication::UnicodeUTF8));
        actionDeleteXray5->setVisible(false);
        actionDeleteNeutron1->setText(QApplication::translate("MainWindow", "Sample 1", 0, QApplication::UnicodeUTF8));
        actionDeleteNeutron1->setVisible(false); //default to hidden, only show when loaded later
        actionDeleteNeutron2->setText(QApplication::translate("MainWindow", "Sample 2", 0, QApplication::UnicodeUTF8));
        actionDeleteNeutron2->setVisible(false);
        actionDeleteNeutron3->setText(QApplication::translate("MainWindow", "Sample 3", 0, QApplication::UnicodeUTF8));
        actionDeleteNeutron3->setVisible(false);
        actionDeleteNeutron4->setText(QApplication::translate("MainWindow", "Sample 4", 0, QApplication::UnicodeUTF8));
        actionDeleteNeutron4->setVisible(false);
        actionDeleteNeutron5->setText(QApplication::translate("MainWindow", "Sample 5", 0, QApplication::UnicodeUTF8));
        actionDeleteNeutron5->setVisible(false);
        actionElectron_density_profile->setText(QApplication::translate("MainWindow", "&Electron density profile", 0, QApplication::UnicodeUTF8));
        actionNeutron_Scattering_Length_Density->setText(QApplication::translate("MainWindow", "&Neutron scattering length density", 0, QApplication::UnicodeUTF8));
        actionComponent_file->setText(QApplication::translate("MainWindow", "&Component file", 0, QApplication::UnicodeUTF8));
        action_Atomic_form_factors->setText(QApplication::translate("MainWindow", "&Atomic form factors", 0, QApplication::UnicodeUTF8));
        actionSi_mulation_specifics->setText(QApplication::translate("MainWindow", "Si&mulation details", 0, QApplication::UnicodeUTF8));
        action_Analysis->setText(QApplication::translate("MainWindow", "&Analysis", 0, QApplication::UnicodeUTF8));
        actionEverything->setText(QApplication::translate("MainWindow", "Every&thing", 0, QApplication::UnicodeUTF8));
        actionElementalNumb_density->setText(QApplication::translate("MainWindow", "Elemental", 0, QApplication::UnicodeUTF8));
        actionParticleNumb_density->setText(QApplication::translate("MainWindow", "Particles", 0, QApplication::UnicodeUTF8));
        actionComponentNumb_density->setText(QApplication::translate("MainWindow", "Components", 0, QApplication::UnicodeUTF8));
        actionElementalElectron_density->setText(QApplication::translate("MainWindow", "&Elemental", 0, QApplication::UnicodeUTF8));
        actionComponentElectron_density->setText(QApplication::translate("MainWindow", "&Component", 0, QApplication::UnicodeUTF8));
        actionElementalNeutron_SL_density->setText(QApplication::translate("MainWindow", "Elemental", 0, QApplication::UnicodeUTF8));
        actionComponentNeutron_SL_density->setText(QApplication::translate("MainWindow", "Component", 0, QApplication::UnicodeUTF8));
        action_X_ray_form_factors->setText(QApplication::translate("MainWindow", "&X-ray form factors", 0, QApplication::UnicodeUTF8));
        actionNeutron_form_factors->setText(QApplication::translate("MainWindow", "&Neutron form factors", 0, QApplication::UnicodeUTF8));
        actionVolumetric_fit->setText(QApplication::translate("MainWindow", "&Volumetric fit", 0, QApplication::UnicodeUTF8));
        actionFitToWindow->setText(QApplication::translate("MainWindow", "&Fit plot to window", 0, QApplication::UnicodeUTF8));
        actionFitToWindow->setShortcut(QApplication::translate("MainWindow", "Ctrl+A", 0, QApplication::UnicodeUTF8));
        actionTogglePlot->setText(QApplication::translate("MainWindow", "&Toggle full screen plot", 0, QApplication::UnicodeUTF8));
        actionTogglePlot->setShortcut(QApplication::translate("MainWindow", "Ctrl+T", 0, QApplication::UnicodeUTF8));
        actionPlotAdvanced->setText(QApplication::translate("MainWindow", "&Advanced", 0, QApplication::UnicodeUTF8));
        actionAbout_SIMtoEXP->setText(QApplication::translate("MainWindow", "About SIMtoEXP", 0, QApplication::UnicodeUTF8));
        actionUser_manual->setText(QApplication::translate("MainWindow", "User manual", 0, QApplication::UnicodeUTF8));
        actionLicense->setText(QApplication::translate("MainWindow", "License", 0, QApplication::UnicodeUTF8));
        actionScattering_lengths->setText(QApplication::translate("MainWindow", "&Scattering lengths", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(e_densities_tab), QApplication::translate("MainWindow", "Electron Densities", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(neutron_SL_tab), QApplication::translate("MainWindow", "Neutron SL Densities", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(xray_formfactors_tab), QApplication::translate("MainWindow", "X-ray Form Factors", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(neutron_formfactors_tab), QApplication::translate("MainWindow", "Neutron Form Factors", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(num_densities_tab), QApplication::translate("MainWindow", "Number Densities", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(vol_probs_tab), QApplication::translate("MainWindow", "Volume Probabilities", 0, QApplication::UnicodeUTF8));

        left_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Left:</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        right_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Right:</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        calc_volume_button->setText(QApplication::translate("MainWindow", "Calculate volumes", 0, QApplication::UnicodeUTF8));
        rms_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">rms</span>:</p></body></html>", 0, QApplication::UnicodeUTF8));
        fourier_button->setText(QApplication::translate("MainWindow", "Fourier Transform", 0, QApplication::UnicodeUTF8));
        sym_checkBox->setText(QApplication::translate("MainWindow", "Symmetrized", 0, QApplication::UnicodeUTF8));
        defaults_button->setText(QApplication::translate("MainWindow", "Reset defaults", 0, QApplication::UnicodeUTF8));
        solv_ed_label->setText(QApplication::translate("MainWindow", "Solvent ED", 0, QApplication::UnicodeUTF8));
        solv_ed_lineEdit->setText(QApplication::translate("MainWindow", "0.333", 0, QApplication::UnicodeUTF8));
        solv_nsld_label->setText(QApplication::translate("MainWindow", "Solvent NSLD", 0, QApplication::UnicodeUTF8));
        solv_nsld_lineEdit->setText(QApplication::translate("MainWindow", "6.38E-6", 0, QApplication::UnicodeUTF8));
        q_int_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">q Interval:</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        low_label->setText(QApplication::translate("MainWindow", "Low", 0, QApplication::UnicodeUTF8));
        high_label->setText(QApplication::translate("MainWindow", "High", 0, QApplication::UnicodeUTF8));
        step_label->setText(QApplication::translate("MainWindow", "Step", 0, QApplication::UnicodeUTF8));
        xray_int_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">X-ray</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        xray_qlow_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        xray_qhigh_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        xray_qstep_lineEdit->setText(QApplication::translate("MainWindow", "0.001", 0, QApplication::UnicodeUTF8));
        neutron_int_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#800000;\">Neutron</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        neut_qlow_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        neut_qhigh_lineEdit->setText(QApplication::translate("MainWindow", "0.4", 0, QApplication::UnicodeUTF8));
        neut_qstep_lineEdit->setText(QApplication::translate("MainWindow", "0.0025", 0, QApplication::UnicodeUTF8));

        cmp_labels[CMP_ID_INDEX]->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        cmp_labels[CMP_NATOMS_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p># Atom</p></body></html>", 0, QApplication::UnicodeUTF8));
        cmp_labels[CMP_ATOMS_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p>Atom/grp</p></body></html>", 0, QApplication::UnicodeUTF8));
        cmp_labels[CMP_NGROUPS_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p># grps</p></body></html>", 0, QApplication::UnicodeUTF8));
        cmp_labels[CMP_NELEC_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p># e<span style=\" vertical-align:super;\">-</span>/grp</p></body></html>", 0, QApplication::UnicodeUTF8));
        cmp_labels[CMP_NSLD_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p>SL<span style=\" vertical-align:sub;\">n</span>/grp</p></body></html>", 0, QApplication::UnicodeUTF8));
        cmp_labels[CMP_VOLUME_PGROUP_INDEX]->setText(QApplication::translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">grp</span></p></body></html>", 0, QApplication::UnicodeUTF8));

        //ids have nothing in them
        for(int i = 0; i < id_edits.size(); i++)
            id_edits[i]->setText(QApplication::translate("MainWindow", "", 0, QApplication::UnicodeUTF8));

        //loop through rest of line edits to set text
        for(int i = 1; i < cmp_edits.size(); i++)
            for(int j = 0; j < COMPONENT_ROWS; j++)
                (*cmp_edits[i])[j]->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));

        xray_sample_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">X-ray</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        xray_scale_button->setText(QApplication::translate("MainWindow", "Scale", 0, QApplication::UnicodeUTF8));
        xray_chi_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>\317\207<span style=\" vertical-align:super;\">2</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        xray_sam1_label->setText(QApplication::translate("MainWindow", "1", 0, QApplication::UnicodeUTF8));
        xray_scale_sam1_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        xray_chi_sam1_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        xray_sam2_label->setText(QApplication::translate("MainWindow", "2", 0, QApplication::UnicodeUTF8));
        xray_scale_sam2_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        xray_chi_sam2_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        xray_sam3_label->setText(QApplication::translate("MainWindow", "3", 0, QApplication::UnicodeUTF8));
        xray_scale_sam3_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        xray_chi_sam3_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        xray_sam4_label->setText(QApplication::translate("MainWindow", "4", 0, QApplication::UnicodeUTF8));
        xray_scale_sam4_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        xray_chi_sam4_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        xray_sam5_label->setText(QApplication::translate("MainWindow", "5", 0, QApplication::UnicodeUTF8));
        xray_scale_sam5_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        xray_chi_sam5_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        neut_sample_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p><span style=\" color:#800000;\">Neutron</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        neut_scale_button->setText(QApplication::translate("MainWindow", "Scale", 0, QApplication::UnicodeUTF8));
        neut_chi_label->setText(QApplication::translate("MainWindow", "<html><head/><body><p>\317\207<span style=\" vertical-align:super;\">2</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        neut_sam1_label->setText(QApplication::translate("MainWindow", "", 0, QApplication::UnicodeUTF8));
        neut_scale_sam1_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        neut_chi_sam1_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        neut_sam2_label->setText(QApplication::translate("MainWindow", "", 0, QApplication::UnicodeUTF8));
        neut_scale_sam2_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        neut_chi_sam2_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        neut_sam3_label->setText(QApplication::translate("MainWindow", "", 0, QApplication::UnicodeUTF8));
        neut_scale_sam3_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        neut_chi_sam3_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        neut_sam4_label->setText(QApplication::translate("MainWindow", "", 0, QApplication::UnicodeUTF8));
        neut_scale_sam4_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        neut_chi_sam4_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        neut_sam5_label->setText(QApplication::translate("MainWindow", "", 0, QApplication::UnicodeUTF8));
        neut_scale_sam5_lineEdit->setText(QApplication::translate("MainWindow", "1.0", 0, QApplication::UnicodeUTF8));
        neut_chi_sam5_lineEdit->setText(QApplication::translate("MainWindow", "0.0", 0, QApplication::UnicodeUTF8));
        menu_File->setTitle(QApplication::translate("MainWindow", "&File", 0, QApplication::UnicodeUTF8));
        menuOpen->setTitle(QApplication::translate("MainWindow", "&Open", 0, QApplication::UnicodeUTF8));
        menuSimulation_data->setTitle(QApplication::translate("MainWindow", "&Simulation data", 0, QApplication::UnicodeUTF8));
        menuStructureFactor_data->setTitle(QApplication::translate("MainWindow", "S&tructure factors", 0, QApplication::UnicodeUTF8));
        menuDelete->setTitle(QApplication::translate("MainWindow", "&Delete", 0, QApplication::UnicodeUTF8));
        menuXrayDelete->setTitle(QApplication::translate("MainWindow", "&X-ray", 0, QApplication::UnicodeUTF8));
        menuNeutronDelete->setTitle(QApplication::translate("MainWindow", "&Neutron", 0, QApplication::UnicodeUTF8));
        menu_Tools->setTitle(QApplication::translate("MainWindow", "&Tools", 0, QApplication::UnicodeUTF8));
        menuE_xport->setTitle(QApplication::translate("MainWindow", "E&xport", 0, QApplication::UnicodeUTF8));
        menuExpNumberDensity->setTitle(QApplication::translate("MainWindow", "&Number Density", 0, QApplication::UnicodeUTF8));
        menuExpElectDensity->setTitle(QApplication::translate("MainWindow", "&Electron Density", 0, QApplication::UnicodeUTF8));
        menuExpNSLDensity->setTitle(QApplication::translate("MainWindow", "Neutron &SL Density", 0, QApplication::UnicodeUTF8));
        menu_Window->setTitle(QApplication::translate("MainWindow", "&Window", 0, QApplication::UnicodeUTF8));
        menu_Help->setTitle(QApplication::translate("MainWindow", "&Help", 0, QApplication::UnicodeUTF8));
    } // retranslateUi
#endif

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // SIMTOEXP_MWZ13889_H


